### ISSUE TITLE
ImportError: No module named typing

### ISSUE THREAD

**Issue by BalestraPatrick** [uber/uber-poet#30]
Hello! I followed the instructions like it's mentioned in the README, but I get the following error: `ImportError: No module named typing`.

Here's the full log:
```shell
$ pipenv run ./genproj.py --output_directory "$HOME/Desktop/mockapp" \
                        --buck_module_path "/mockapp" \
                        --gen_type flat \
                        --lines_of_code 150000
Traceback (most recent call last):
  File "./genproj.py", line 17, in <module>
    from uberpoet.genproj import GenProjCommandLine
  File "/Users/patrickb/Downloads/uber-poet-master/uberpoet/genproj.py", line 22, in <module>
    from . import commandlineutil, projectgen
  File "/Users/patrickb/Downloads/uber-poet-master/uberpoet/commandlineutil.py", line 25, in <module>
    from . import dotreader
  File "/Users/patrickb/Downloads/uber-poet-master/uberpoet/dotreader.py", line 23, in <module>
    from typing import Dict, List, Set  # noqa: F401
ImportError: No module named typing
```

My Environment:
```
$ python --version
Python 2.7.10
$ xcodebuild -version
Xcode 10.2
Build version 10E125
```

Thank you!

**Comment by mahyar** [comment]
Ah I think you have to do pipenv install —dev first.  Didn't quite realize that.

Im on vacation now, but I will fix the readme when I get back in a bit.

**Comment by uber-mahyar2** [comment]
Reproduced your issues and confirmed it was a missing `pipenv install` command that caused your error.  Edited the readme to tell you to run pipenv install.

**Comment by flutterq** [comment]
[[Solved] Pip command line “ImportError: No Module Named Typing”](https://exerror.com/solved-pip-command-line-importerror-no-module-named-typing/)
